### ISSUE TITLE
Beta: Dark Grey text is too unreadable in Dark Theme

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#551]
For example in settings:

![http://i.imgur.com/qAQEVV6.png](http://i.imgur.com/qAQEVV6.png)

```css
.dark {
    color: #444;
}
```
