### ISSUE TITLE
Modifiers and Delimiters menus show as dark when light theme is used

### ISSUE THREAD

**Issue by jay** [firasdib/Regex101#665]
I use the light theme but the modifiers and delimiters menu show in the dark theme. I tried in Firefox and Chrome.

**Comment by firasdib** [comment]
Not sure I follow. Are you referring to the fact that the menus are dark grey? If so, thats intended.

**Comment by jay** [comment]
Yes, it's harder for me to see and read. 

here is how it looks now in a light theme:
![clipboard02](https://cloud.githubusercontent.com/assets/965580/18928422/055e5e74-858e-11e6-9747-2e2dd82a10cf.png)

here is how i would do it in a light theme:
![clipboard03](https://cloud.githubusercontent.com/assets/965580/18928427/0b61ca18-858e-11e6-86f4-a800a1174ade.png)

the colors I used are purple #5319E7 for the modifier name, #FF2597 for the modifier letter, black for the modifier description, white for the background. i'm not suggesting you use those colors but that's an example of something that's easy for me to read: text on a white background

**Comment by Ouims** [comment]
I agree about this, not sure why these are using dark colour, maybe just use white background , bolded black letter for the modifier and the rest just normal black?

**Comment by firasdib** [comment]
Its grey because I think it looks better. A white or light grey menu looks out of place and gets lost in the background.

**Comment by TWiStErRob** [comment]
I don't think blending in is such a bad thing. If you check the dark menu with the dark theme it blends in nicely. While, with the light theme the menu stands out; making it look more important than it is. Windows, Mac, Android all agree about having background and menu color almost the same shade.

Another concern you should take into account is that on a sunny day this gray-on-gray menu is really hard to read. As soon as it appears I can almost feel my pupils adjusting to be able to read the text.

I also think that the existing shadow + border should pretty much make the "lost in background" concern go away. I like @jay's mockup, though purple/pink is a little too much, the site's accent color is blue; I would prefer black for heading, something bold/dark-colored for the actual flag letters and dark gray for explanation. Something like:
![image](https://cloud.githubusercontent.com/assets/2906988/18957657/32ca6ef2-8660-11e6-894b-23282eb9a04e.png)

```css
/* popup menu */
.light [role="menu"] { background: #FFF; }
/* popup menu header */
.light [role="menu"] ._2OO0XDKJJvOUzRER1baV5h { color: #344f71; }
/* menu item */
.light [role="menu"] ._1BHlDmQxD00DXzFRSzFNL3 { color: #457abb; }
.light [role="menu"] ._1BHlDmQxD00DXzFRSzFNL3:hover { background: #eee; }
/* text inside the item */
.light [role="menu"] ._2UYTOj70cHKj59X8NX8Pie { color: #000; }
.light [role="menu"] ._2UYTOj70cHKj59X8NX8Pie > strong { color: #457abb; font-size: 125%; }
/* tick hidden */
._1wR93hZ06YfJ1Zqc1v_bWg._1Zo5GTTdgMrsOQhvYgXdrw { visibility: visible; opacity: 0.1; }
```
