### ISSUE TITLE
css tweak on #copycontainer in export matches

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#678]
If the export list is too long and a scroll bar needs to be rendered, the copy button overlaps the scroll bar (FF, Chrome, Safari...).
![copy icon](https://bugout.regex.cf/copycontainer.png)

```css
.copyBtn {
  ...
  right: 18px; /* was 5px; */
  ...
}
```
The above may not look as good in scenarios where there's no overflow past the parent container.
